#!/bin/bash

read -p "Choose VM name: " name
dir=$HOME/VMs/data/$name

[ -f $dir ] &&
  read -p "a VM with this name exists, would you like to delete it? [y,N]: " answer &&
  [ "$answer" == "y" ] && 
  rm -rf $dir  # haha funny rm -rf

mkdir $dir




read -p "use existing disk image? [y,N]" answer
if [ "$answer" == "y" ]; then
  read -p "Enter path to disk image: " disk_path
  
  [ ! -f $disk_path ] && echo "$disk_path doesnt exist!" && exit 1
  mv $disk_path $dir/disk.qcow2

else
  # read -p "choose fs format: " fs
  # available=$(df -h | grep /dev/nvme0n1p7) &&
  read -p "Choose disk size: " disk_size
  qemu-img create -f qcow2 $dir/disk.qcow2 $disk_size

  # the iso choice method sucks, fix this :)
  iso_files=("", $(ls $HOME/VMs/iso))
  length=$((${#iso_files[@]}-1))

  for i in $(seq 1 $length); do
    echo "$i. ${iso_files[$i]}"
  done

  read -p "Choose .iso file [1-$length]: " iso_index
  iso="$HOME/VMs/iso/${iso_files[$iso_index]}"
fi


read -p "Choose RAM [default=2G]: " ram
[ "$ram" == "" ] && ram="2G"


read -p "Choose cpu cores: " cpu
# add cpu model (from recommended options)


echo "ram=$ram" >> $dir/config
echo "cpu=$cpu" >> $dir/config


qemu-system-x86_64 -enable-kvm \
  -cdrom $iso -boot d -drive file=$dir/disk.qcow2 \
  -cpu host \
  -m $ram  \
  -vga virtio -display sdl,gl=on
