#!/bin/bash

[ "$1" == "" ] && echo "invalid argument" && exit 1

dir=$HOME/VMs/data/$1

while IFS='=' read -r key value; do
  [[ $key && $value ]] &&
  declare "$key=$value"
done < $dir/config

[ "$ram" == "" ] && ram="2G"
[ "$cpu" == "" ] && cpu="1"

qemu-system-x86_64 \
  -enable-kvm \
  -boot c -drive file=$dir/disk.qcow2 \
  -cpu host -smp $cpu \
  -m $ram \
  -vga virtio -display sdl,gl=on &
